name: flutter_mjpeg
description: Flutter widget to show mjpeg stream from URL, mainly used by ip camera, stop itself when not on screen
version: 1.2.8
homepage: https://github.com/mylisabox/flutter_mjpeg

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.7.8 <2.0.0"

dependencies:
  flutter_widgets: ^0.1.12
  flutter_hooks: ^0.9.0
  http: ^0.12.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
