name: flutter_mjpeg
description: Flutter widget to show mjpeg stream from URL, mainly used by ip camera, stop itself when not on screen
version: 2.0.0
homepage: https://github.com/mylisabox/flutter_mjpeg

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.7.8 <2.0.0"

dependencies:
  visibility_detector: ">=0.2.0-nullsafety.1 <1.0.0"
  flutter_hooks: ">=0.16.0 <1.0.0"
  http: ">=0.13.1 <1.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
